### ISSUE TITLE
Failed to build Qt6 packages from git repository on Windows in development mode

### ISSUE THREAD

**Issue by karen-arutyunov** [build2-packaging/Qt6#1]
Trying to build Qt6 packages on my local Windows VM in the development mode ends up with the following error:

```
> bpkg build https://github.com/build2-packaging/Qt6.git#master
...
distributing Qt6Moc/6.2.2-a.0.20220406125328.837025e703c5 [.bpkg\host\]
error: unable to stat .bpkg\tmp\d3689569d718\Qt6Moc\moc\3rdparty\freebsd: access is denied
```
This happens due to absence of the symlink=dir attributes specification for the directory symlinks in the .gitattributes files (see https://github.com/git-for-windows/git/commit/25a7f44187bb9d208ec34401b5b25db4641127d6 for details).

I believe that creation of the corresponding .gitattributes files needs to be added to the generate script. See the dir-attr branch for the .gitattributes files to be created.

Btw, CI-ing with windows_10_devmode-msvc_16.11 target configuration strangely doesn't fail (didn't manage to investigate why since the bastion IP seems to be changed).

**Comment by francoisk** [comment]
Thanks, I've pushed the changes to the `review` branch.
